name: Playright Tests

on:
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t playwright-tests .
          
      - name: Run tests for different users
        continue-on-error: true
        run: |
          mkdir -p reports
          
          for USER in standard_user problem_user error_user
          do 
            echo "Running tests for $USER"

            docker run --rm \
              -e USERNAME=$USER \
              -v $PWD/reports/$USER:/app/playwright-report \
              playwright-tests || true
          done           

      - name: Show generated files
        run: ls $PWD/reports

      - name: Prepare Github Pages content 
        run: |
          mkdir -p public
          cp -r reports/* public/


          # Index page
          cat <<EOF > public/index.html
          <html>
            <body>
              <h1> Playwright Reports</h1>
              <ul>
                <li><a href = "./standard_user/"> standard_user Report</a></li>
                <li><a href = "./problem_user/"> problem_user Report</a></li>
                <li><a href = "./error_user/"> error_user Report</a></li>
              </ul>
            </body>
          </html>
          EOF     

      - name: Upload Pages artifact          
        uses: actions/upload-pages-artifact@v3    
        with:
          path: public 
          
      - name: Deploy to Github Pages 
        uses: actions/deploy-pages@v4
